Repository boostcampwm-2024/iOS08-Shook, pull requests merged in 2024-12, with the labels that each got.

#282 task hotfix 가로모드 시 키보드 내리기
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
Labels: fix

#283 task hotfix 마이크 버튼 안보이도록 처리
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastViewController.swift
  Projects/Features/MainFeature/Sources/ViewControllers/SettingUIViewController.swift
Labels: fix, chore

#284 task hotfix 방송 설명 없을 시 Unknown 옆에 . 표시되는 문제 해결
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
Labels: chore

#287 task hotfix chtting UI
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
Labels: fix, chore

#294 task readme 업데이트
  README.md
Labels: chore

#296 task 히어로 애니메이션 수정 및 주석 작성
  Projects/Features/MainFeature/Sources/Utilities/CollectionViewCellTransitioning.swift
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastCollectionViewController.swift
Labels: design, chore

#297 task hotfix chatting UI 개선
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
Labels: fix
