Repository boostcampwm-2024/iOS08-Shook, pull requests merged in 2024-11, with the labels that each got.

#3 task #1 tuist 프로젝트 init
  .gitignore
  .mise.toml
  IOS08Shook/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  IOS08Shook/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  IOS08Shook/Resources/Assets.xcassets/Contents.json
  IOS08Shook/Resources/LaunchScreen.storyboard
  IOS08Shook/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  IOS08Shook/Sources/ContentView.swift
  IOS08Shook/Sources/IOS08ShookApp.swift
  IOS08Shook/Tests/IOS08ShookTests.swift
  Project.swift
  README.md
  Tuist/Package.swift
Labels: feature

#7 task #2 tuist 프로젝트 init
  Scripts/Setup.sh
Labels: chore

#8 task #4 swiftLint 적용
  IOS08Shook/Sources/ContentView.swift
  Project.swift
  Scripts/.swiftlint.yml
  Scripts/SwiftLintRunScript.sh
Labels: feature

#17 task #5 플러그인 스크립트 정의
  Plugin/ConfigurationPlugin/Plugin.swift
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Extension.swift
  Project.swift
  Scripts/generatePlugin.swift
  Tuist/Config.swift
  makefile
Labels: feature

#18 task #6 swift format 적용
  .gitconfig
  .githooks/pre-push
  .swiftformat
  IOS08Shook/Sources/ContentView.swift
  IOS08Shook/Tests/IOS08ShookTests.swift
Labels: feature

#19 story Tuist 생성 및 Scripts 생성
  .gitconfig
  .githooks/pre-push
  .gitignore
  .mise.toml
  .swiftformat
  IOS08Shook/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  IOS08Shook/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  IOS08Shook/Resources/Assets.xcassets/Contents.json
  IOS08Shook/Resources/LaunchScreen.storyboard
  IOS08Shook/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  IOS08Shook/Sources/ContentView.swift
  IOS08Shook/Sources/IOS08ShookApp.swift
  IOS08Shook/Tests/IOS08ShookTests.swift
  Plugin/ConfigurationPlugin/Plugin.swift
  Plugin/ConfigurationPlugin/ProjectDescriptionHelpers/Configuration+Extension.swift
  Project.swift
  README.md
  Scripts/.swiftlint.yml
  Scripts/Setup.sh
  Scripts/SwiftLintRunScript.sh
  Scripts/generatePlugin.swift
  Tuist/Config.swift
  Tuist/Package.swift
  makefile
Labels: feature

#21 task #10 Environment 플러그인 정의
  Plugin/EnvironmentPlugin/Plugin.swift
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Tuist/Config.swift
Labels: chore

#22 task #11 템플릿 플러그인 정의
  Plugin/TemplatePlugin/Plugin.swift
  Plugin/TemplatePlugin/ProjectDescriptionHelpers/Extensions/ResourceFileElements+Extension.swift
  Plugin/TemplatePlugin/ProjectDescriptionHelpers/Extensions/SourceFilesList+Extension.swift
  Plugin/TemplatePlugin/Templates/Demo/Demo.swift
  Plugin/TemplatePlugin/Templates/Demo/DemoResources.stencil
  Plugin/TemplatePlugin/Templates/Demo/DemoSources.stencil
  Plugin/TemplatePlugin/Templates/Interface/interface.stencil
  Plugin/TemplatePlugin/Templates/Interface/interface.swift
  Plugin/TemplatePlugin/Templates/Sources/Sources.stencil
  Plugin/TemplatePlugin/Templates/Sources/Sources.swift
  Plugin/TemplatePlugin/Templates/Testing/Testing.stencil
  Plugin/TemplatePlugin/Templates/Testing/Testing.swift
  Plugin/TemplatePlugin/Templates/Tests/Tests.stencil
  Plugin/TemplatePlugin/Templates/Tests/Tests.swift
  Tuist/Config.swift
Labels: chore

#24 task #12 워크스페이스를 이용하여 프로젝트를 추적
  Projects/App/Project.swift
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Resources/Assets.xcassets/Contents.json
  Projects/App/Resources/LaunchScreen.storyboard
  Projects/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/IOS08ShookApp.swift
  Projects/App/Tests/IOS08ShookTests.swift
  Workspace.swift
Labels: chore

#25 task #13, #14 Extension, TargetSpec 정의
  Plugin/EnvironmentPlugin/ProjectDescriptionHelpers/ProjectEnvironment.swift
  Projects/App/Project.swift
  Projects/App/Resources/Preview Content/Preview Assets.xcassets/Contents.json
  Projects/App/Sources/AppDelegate.swift
  Projects/App/Sources/IOS08ShookApp.swift
  Projects/App/Sources/SceneDelegate.swift
  Tuist/ProjectDescriptionHelpers/Environment/GenerationEnvironment.swift
  Tuist/ProjectDescriptionHelpers/Extensions/InfoPlist+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Project+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Scheme+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/SettingsDictionary+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/TargetScript+Extension.swift
  Tuist/ProjectDescriptionHelpers/Protocol/Configurable.swift
  Tuist/ProjectDescriptionHelpers/TargetSpec/TargetSpec.swift
Labels: chore

#27 task #15 모듈 자동 생성 스크립트
  Scripts/generateModule.swift
Labels: chore

#28 task #16 기본 모듈 생성 및 install HaishinKit
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Plugin/TemplatePlugin/Templates/Interface/Interface.stencil
  Plugin/TemplatePlugin/Templates/Interface/Interface.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domains/BaseDomain/Interface/Interface.swift
  Projects/Domains/BaseDomain/Project.swift
  Projects/Domains/BaseDomain/Sources/Sources.swift
  Projects/Domains/BaseDomain/Testing/Testing.swift
  Projects/Domains/BaseDomain/Tests/BaseDomainTest.swift
  Projects/Features/BaseFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/BaseFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/BaseFeature/Interface/Interface.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/Sources.swift
  Projects/Features/BaseFeature/Testing/Testing.swift
  Projects/Features/BaseFeature/Tests/BaseFeatureTest.swift
  Projects/Modules/ThirdPartyLibModule/Interface/Interface.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  Projects/Modules/ThirdPartyLibModule/Sources/Sources.swift
  Projects/Modules/ThirdPartyLibModule/Tests/ThirdPartyLibModuleTest.swift
  Projects/UserInterfaces/DesignSystem/Interface/Interface.swift
  Projects/UserInterfaces/DesignSystem/Project.swift
  Projects/UserInterfaces/DesignSystem/Resources/Color.xcassets/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Color.xcassets/PrimaryColor.colorset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/tuist.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/tuist.imageset/tuist 1.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/tuist.imageset/tuist 2.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/tuist.imageset/tuist.png
  Projects/UserInterfaces/DesignSystem/Sources/Sources.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
  graph.png
Labels: chore

#33 task #32 Network 모듈 생성 및 의존성 설정
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Modules/NetworkModule/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/NetworkModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/NetworkModule/Interface/Interface.swift
  Projects/Modules/NetworkModule/Project.swift
  Projects/Modules/NetworkModule/Sources/Sources.swift
  Projects/Modules/NetworkModule/Testing/Testing.swift
  Projects/Modules/NetworkModule/Tests/NetworkModuleTest.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  graph.png
Labels: chore

#34 task #31 EasyLayout 모듈 생성
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Modules/EasyLayoutModule/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/EasyLayoutModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/EasyLayoutModule/Project.swift
  Projects/Modules/EasyLayoutModule/Sources/Sources.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  graph.png
Labels: chore

#35 story Network 모듈 추가 및 의존성 설정
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Modules/NetworkModule/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/NetworkModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/NetworkModule/Interface/Interface.swift
  Projects/Modules/NetworkModule/Project.swift
  Projects/Modules/NetworkModule/Sources/Sources.swift
  Projects/Modules/NetworkModule/Testing/Testing.swift
  Projects/Modules/NetworkModule/Tests/NetworkModuleTest.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  graph.png
Labels: chore

#36 story EasyLayout 모듈 생성
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Modules/EasyLayoutModule/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/EasyLayoutModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/EasyLayoutModule/Project.swift
  Projects/Modules/EasyLayoutModule/Sources/Sources.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  graph.png
Labels: chore

#43 task #40 상수값을 통해 Width Height 설정 기능 구현
  Projects/Modules/EasyLayoutModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyLayout.swift
  Projects/Modules/EasyLayoutModule/Sources/Extension/UIView+.swift
  Projects/Modules/EasyLayoutModule/Sources/Sources.swift
Labels: feature, chore

#44 task #41 width와 height를 동시에 설정하는 기능
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: feature, chore

#45 story 자기 자신과 관련된 속성인 width, height 속성 구현
  Projects/Modules/EasyLayoutModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyLayout.swift
  Projects/Modules/EasyLayoutModule/Sources/Extension/UIView+.swift
  Projects/Modules/EasyLayoutModule/Sources/Sources.swift
Labels: feature, chore

#50 task #39 RequstTask별 알맞은 reuqst param을 적용
  Projects/Modules/NetworkModule/Sources/Request/Encoding/ParamterJSONEncoder.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/RequestParameterEncodable.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/URLQueryEncoder.swift
  Projects/Modules/NetworkModule/Sources/Request/RequestTask.swift
  Projects/Modules/NetworkModule/Tests/NetworkModuleTest.swift
Labels: enhancement

#49 task #48 요청 오류 적용
  Projects/Modules/NetworkModule/Sources/Request/Encoding/ParamterJSONEncoder.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/URLQueryEncoder.swift
  Projects/Modules/NetworkModule/Sources/Request/RequestError.swift
Labels: feature

#58 task #52 뷰의 horizontality, vertical, diagonal 제약 조건을 설정할 수 있는 기능 구현
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/Anchor.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyLayout.swift
  Projects/Modules/EasyLayoutModule/Sources/Extension/UIView+.swift
  Projects/Modules/EasyLayoutModule/Sources/Protocol/Anchorable.swift
Labels: feature

#60 task Hotfix 모듈러 아키텍처 의존성 누락
  Scripts/generateModule.swift
Labels: bug

#62 tast #57 Client 테스트
  Projects/Domains/BaseDomain/Project.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Modules/NetworkModule/Interface/URLSessionProtocol.swift
  Projects/Modules/NetworkModule/Project.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Endpoint.swift
  Projects/Modules/NetworkModule/Testing/MockData.swift
  Projects/Modules/NetworkModule/Testing/MockResponse.swift
  Projects/Modules/NetworkModule/Testing/MockURLSession.swift
  Projects/Modules/NetworkModule/Testing/Testing.swift
  Projects/Modules/NetworkModule/Tests/MockEndpoint.swift
  Projects/Modules/NetworkModule/Tests/NetworkClientTest.swift
  Projects/Modules/NetworkModule/Tests/NetworkEncoderTests.swift
  graph.png
Labels: test

#61 story 상대 뷰를 기준으로 Position 관련 레이아웃 인터페이스 구현
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/Anchor.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyLayout.swift
  Projects/Modules/EasyLayoutModule/Sources/Extension/UIView+.swift
  Projects/Modules/EasyLayoutModule/Sources/Protocol/Anchorable.swift
Labels: feature

#64 task 코드리뷰 반영
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Error/HTTPError.swift
  Projects/Modules/NetworkModule/Sources/Error/NetworkError.swift
  Projects/Modules/NetworkModule/Sources/Request/Components/HTTPMethod.swift
  Projects/Modules/NetworkModule/Sources/Request/Components/RequestTask.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/RequestParameterEncodable.swift
  Projects/Modules/NetworkModule/Sources/Response/Response.swift
Labels: refactor

#65 task #63 offset & padding 파라미터 추가
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: feature

#70 task #68 Network에 대한 Default Logger 구현
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/DefaultLoggingInterceptor.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/Interceptor.swift
  Projects/Modules/NetworkModule/Tests/MockEndpoint.swift
  Projects/Modules/NetworkModule/Tests/NetworkClientTest.swift
Labels: enhancement

#69 test #67 URLProtocol 적용
  Projects/Modules/NetworkModule/Interface/URLSessionProtocol.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/Interceptor.swift
  Projects/Modules/NetworkModule/Testing/MockURLProtocol.swift
  Projects/Modules/NetworkModule/Testing/MockURLSession.swift
  Projects/Modules/NetworkModule/Tests/MockEndpoint.swift
  Projects/Modules/NetworkModule/Tests/NetworkClientTest.swift
Labels: test

#72 story 네트워크 요청, 응답, 로그
  Projects/Domains/BaseDomain/Project.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/Sources.swift
  Projects/Modules/NetworkModule/Project.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Client/Requestable.swift
  Projects/Modules/NetworkModule/Sources/Endpoint.swift
  Projects/Modules/NetworkModule/Sources/Error/HTTPError.swift
  Projects/Modules/NetworkModule/Sources/Error/NetworkError.swift
  Projects/Modules/NetworkModule/Sources/Extensions/URL+Extension.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/DefaultLoggingInterceptor.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/Interceptor.swift
  Projects/Modules/NetworkModule/Sources/Request/Components/HTTPMethod.swift
  Projects/Modules/NetworkModule/Sources/Request/Components/RequestTask.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/ParamterJSONEncoder.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/RequestParameterEncodable.swift
  Projects/Modules/NetworkModule/Sources/Request/Encoding/URLQueryEncoder.swift
  Projects/Modules/NetworkModule/Sources/Response/Response.swift
  Projects/Modules/NetworkModule/Sources/Sources.swift
  Projects/Modules/NetworkModule/Testing/MockData.swift
  Projects/Modules/NetworkModule/Testing/MockResponse.swift
  Projects/Modules/NetworkModule/Testing/MockURLProtocol.swift
  Projects/Modules/NetworkModule/Testing/Testing.swift
  Projects/Modules/NetworkModule/Tests/MockEndpoint.swift
  Projects/Modules/NetworkModule/Tests/NetworkClientTest.swift
  Projects/Modules/NetworkModule/Tests/NetworkEncoderTests.swift
  Projects/Modules/NetworkModule/Tests/NetworkModuleTest.swift
  Scripts/generateModule.swift
  graph.png
Labels: feature

#77 task #75 Anchorable 타입을 파라미터로 받을 수 있도록 구현
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: feature

#76 task #74 Anchor enum -> struct로 변경
  Projects/Modules/EasyLayoutModule/Sources/Anchor.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: enhancement

#79 gitAction을 통해 CI 적용
  .github/workflows/CI.yml
  .gitignore
  Package.resolved
  Package.swift
  Projects/Features/BaseFeature/Sources/Sources.swift
  makefile
Labels: enhancement

#80 story easy layout 사용성 개선
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Sources/Anchor.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: enhancement

#78 task Hotfix 코드리뷰 반영
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Extensions/URL+Extension.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/DefaultLoggingInterceptor.swift
  Projects/Modules/NetworkModule/Sources/Interceptor/Interceptor.swift
  Projects/Modules/NetworkModule/Sources/Request/Components/RequestTask.swift
  Projects/Modules/NetworkModule/Tests/MockEndpoint.swift
Labels: fix

#81 epic easy layout
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Modules/EasyLayoutModule/Demo/Resources/LaunchScreen.storyboard
  Projects/Modules/EasyLayoutModule/Demo/Sources/AppDelegate.swift
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Projects/Modules/EasyLayoutModule/Project.swift
  Projects/Modules/EasyLayoutModule/Sources/Anchor.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyLayout.swift
  Projects/Modules/EasyLayoutModule/Sources/Protocol/Anchorable.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  graph.png
Labels: feature

#85 task 뷰 라이프 사이클 적용
  Projects/Features/BaseFeature/Interface/Interface.swift
  Projects/Features/BaseFeature/Interface/ViewLifeCycle.swift
  Projects/Features/BaseFeature/Interface/ViewModel.swift
  Projects/Features/BaseFeature/Sources/BaseCollectionViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseTableViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseView.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
  Projects/Features/BaseFeature/Sources/Sources.swift
Labels: feature, design

#88 epic feature 생성
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/LiveStreamFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/LiveStreamFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/LiveStreamFeature/Interface/Interface.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Sources.swift
  Projects/Features/LiveStreamFeature/Tests/LiveStreamFeatureTest.swift
  Projects/Features/MainFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Features/MainFeature/Sources/Sources.swift
  Projects/Features/MainFeature/Tests/MainFeatureTest.swift
  Projects/UserInterfaces/DesignSystem/Project.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
  graph.png
Labels: chore

#94 task hotfix contentview는 자동으로 레이아웃 변경되지 않도록
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: fix

#93 task Hotfix 접근제어자 및 주석 수정
  Projects/Features/BaseFeature/Interface/ViewLifeCycle.swift
  Projects/Features/BaseFeature/Sources/BaseCollectionViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseTableViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseView.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
Labels: chore

#100 task #99 높이, 너비 최소 & 최대 크기를 설정할 수 있는 인터페이스 구현
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
Labels: chore

#96 task #95 채팅창 UI 구현
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatEmptyView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#98 task #90 #91 방송설정화면 및 방송 중 화면 구현
  Projects/Features/BaseFeature/Interface/ViewLifeCycle.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/BaseCollectionViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseTableViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseView.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingViewModel.swift
  Projects/Features/MainFeature/Sources/Sources.swift
  Projects/Features/MainFeature/Sources/UITableViewCell+Extension.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature, design

#103 story 방송중화면과 방송 세팅 화면을 구현했습니다.
  Projects/Features/BaseFeature/Interface/ViewLifeCycle.swift
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/BaseCollectionViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseTableViewCell.swift
  Projects/Features/BaseFeature/Sources/BaseView.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingViewModel.swift
  Projects/Features/MainFeature/Sources/Sources.swift
  Projects/Features/MainFeature/Sources/UITableViewCell+Extension.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature, chore

#104 task #89 메인 콜렉션 뷰 구현
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/BaseFeature/Sources/BaseViewController.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BigCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectioinViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/PaddingUILabel.swift
  Projects/Features/MainFeature/Sources/SmallCollectionViewCell.swift
  Projects/Modules/EasyLayoutModule/Sources/EasyConstraint.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature, design

#107 hotfix Error Red 컬러를 추가했습니다.
  Projects/UserInterfaces/DesignSystem/Resources/Color.xcassets/ErrorRed.colorset/Contents.json
Labels: design

#105 story 채팅 화면 구현
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatEmptyView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#108 story 방송 리스트 구현
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BigCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectioinViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/PaddingUILabel.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingViewModel.swift
  Projects/Features/MainFeature/Sources/SmallCollectionViewCell.swift
Labels: feature, design

#110 epic 채팅화면 구현
  Projects/Features/BaseFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatEmptyView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#122 task #117 뷰리스트 + 방송설정화면 연결
  Projects/Features/MainFeature/Sources/BroadcastCollectioinViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingViewModel.swift
Labels: feature

#120 task #101 채팅 입력창 구현
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#118 task #115 다이나믹 레이아웃 적용
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectioinViewController.swift
  Projects/Features/MainFeature/Sources/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/SmallBroadcastCollectionViewCell.swift
Labels: feature, design

#130 task #121 ChatingList DiffableDataSource 적용
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: feature

#132 story 채팅 UI 완료
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#134 epic 채팅 UI
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
Labels: design

#136 task player, chating 화면 병합
  Projects/Features/LiveStreamFeature/Sources/Errors/PlayerError.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: chore

#139 task #135 DIContainer 생성
  Projects/App/Sources/ContentView.swift
  Projects/App/Sources/DIContainer.swift
  Projects/App/Sources/IOS08ShookApp.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Features/LiveStreamFeature/Interface/Interface.swift
  Projects/Features/LiveStreamFeature/Interface/LiveStreamViewControllerFactory.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFractoryImpl.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectioinViewController.swift
Labels: feature, chore

#146 task #119 히어로 애니메이션 구현
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastThumbnailView.swift
  Projects/Features/MainFeature/Sources/CollectionViewCellTransitioning.swift
  Projects/Features/MainFeature/Sources/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/PaddingLabel.swift
  Projects/Features/MainFeature/Sources/SampleLiveStreamingViewController.swift
  Projects/Features/MainFeature/Sources/SmallBroadcastCollectionViewCell.swift
Labels: feature, design

#152 task 플레이어 컨트롤 뷰 자동 닫힘 기능 구현
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: feature

#151 story 방송 리스트 화면 추가
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/BigCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastThumbnailView.swift
  Projects/Features/MainFeature/Sources/CollectionViewCellTransitioning.swift
  Projects/Features/MainFeature/Sources/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/PaddingLabel.swift
  Projects/Features/MainFeature/Sources/SampleLiveStreamingViewController.swift
  Projects/Features/MainFeature/Sources/SmallBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/SmallCollectionViewCell.swift
Labels: feature, design

#155 epic 플레이어 구현
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/PlayerControlView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/ShookPlayerView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/TimeControlView.swift
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomIn_48.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomIn_48.imageset/zoomIn_48@2x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomIn_48.imageset/zoomIn_48@3x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_24.imageset/48@2x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_24.imageset/48@3x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_24.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_24.imageset/Property 1=zoomOut.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_24.imageset/zoomOut.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_48.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_48.imageset/zoomOut_48@2x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/zoomOut_48.imageset/zoomOut_48@3x.png
Labels: feature

#156 epic 채팅 기능 구현 완료
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/ChatingViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: feature

#158 task live stream view controller 레이아웃 수정
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
Labels: chore

#162 task #148 #161 앱그룹으로 소통하기
  Projects/App/BroadcastExtension.entitlements
  Projects/App/BroadcastUploadExtension/Sources/SampleHandler.swift
  Projects/App/Shook.entitlements
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature

#166 task 방만들기 및 방 삭제하기 usecase를 로컬 서버에서 테스트 합니다.
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domains/BaseDomain/Sources/BaseRepository.swift
  Projects/Domains/ChattingDomain/Interface/Repository/ChatRepository.swift
  Projects/Domains/ChattingDomain/Interface/UseCase/DeleteChatRoomUseCase.swift
  Projects/Domains/ChattingDomain/Interface/UseCase/MakeChatRoomUseCase.swift
  Projects/Domains/ChattingDomain/Project.swift
  Projects/Domains/ChattingDomain/Sources/DTO/Request/MakeRoomRequestDTO.swift
  Projects/Domains/ChattingDomain/Sources/DTO/Response/BaseChatDTO.swift
  Projects/Domains/ChattingDomain/Sources/Endpoint/ChatEndpoint.swift
  Projects/Domains/ChattingDomain/Sources/Repository/ChatRepositoryImpl.swift
  Projects/Domains/ChattingDomain/Sources/Usecase/DeleteChatRoomUseCaseImpl.swift
  Projects/Domains/ChattingDomain/Sources/Usecase/MakeChatRoomUseCaseImpl.swift
  Projects/Domains/ChattingDomain/Testing/Testing.swift
  Projects/Domains/ChattingDomain/Tests/ChattingDomainTest.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
  Projects/Features/LiveStreamFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/LiveStreamFeature/Interface/LiveStreamViewControllerFactory.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFractoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
  Projects/Modules/NetworkModule/Sources/Endpoint.swift
  Projects/Modules/NetworkModule/Sources/Extensions/URL+Extension.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature

#159 task #157 Shook 앱에서 뷰 연결
  Projects/App/Sources/MockFetchChannelListUsecaseImpl.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/Domains/LiveStationDomain/Interface/Entity/ChannelEntity.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelListResponseDTO.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/PlayerControlView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/ShookPlayerView.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Demo/Sources/MockFetchChannelListUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamViewControllerFactory.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamingViewController.swift
  Projects/Features/MainFeature/Demo/Sources/MockShookPlayerView.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastThumbnailView.swift
  Projects/Features/MainFeature/Sources/CollectionViewCellTransitioning.swift
  Projects/Features/MainFeature/Sources/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/SampleLiveStreamingViewController.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SmallBroadcastCollectionViewCell.swift
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/chevronDown_24.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/chevronDown_24.imageset/chevronDownCircle-1.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/chevronDown_24.imageset/chevronDownCircle.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/xmark_24.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/xmark_24.imageset/xmarkCircle.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/xmark_24.imageset/xmarkCircle@2x.png
Labels: feature, design

#163 task #160 화면전환시 발생한 오류 수정
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
Labels: fix, design

#173 task #169 방송 수신 Endpoint 구현
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
  Projects/Domains/LiveStationDomain/Sources/Util/ServiceUrlType.swift
Labels: feature

#176 task #175 채널생성 Endpoint 추가
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
  Projects/Domains/LiveStationDomain/Sources/Util/Secrets.swift
Labels: feature

#174 task #170 HaishinKit 의존성 추가
  Projects/Modules/ThirdPartyLibModule/Project.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: chore

#179 task #177 채널 삭제 Endpoint
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
Labels: feature, chore

#181 task #178 썸네일 Endpoint 구현
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
Labels: chore

#180 task #171 모바일 스트리밍 기능 추가
  Projects/App/BroadcastUploadExtension/Sources/SampleHandler.swift
Labels: feature, chore

#184 task #183 썸네일 레포지토리 구성
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ThumbnailResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
Labels: feature

#187 task #186 Live Station Repository 채널 생성 인터페이스 구현
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelListResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
Labels: feature, chore

#192 task #169 Live Station Repository 채널 삭제 인터페이스 구현
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
Labels: feature, chore

#194 story Live Station Repo 구현
  Projects/Domains/LiveStationDomain/Interface/Entity/BroadcastEntity.swift
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/BroadcastResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelListResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ThumbnailResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
  Projects/Modules/NetworkModule/Sources/Client/NetworkClient.swift
Labels: feature, chore

#197 task #172 가로, 세로화면 송출
  Projects/App/BroadcastUploadExtension/Sources/SampleHandler.swift
Labels: feature, chore

#208 task #206 방송중인 리스트가 없을 때 보여줄 화면 구현
  Projects/Features/MainFeature/Sources/BroadcastCollectionEmptyView.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
Labels: design, chore

#204 task #201 AuthFeature 생성 및 의존성 설정
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Features/AuthFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/AuthFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/AuthFeature/Interface/Interface.swift
  Projects/Features/AuthFeature/Project.swift
  Projects/Features/AuthFeature/Sources/Sources.swift
  Projects/Features/AuthFeature/Tests/AuthFeatureTest.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: chore

#200 epic 화면 송출 기능 추가 1차
  Projects/App/BroadcastUploadExtension/Sources/SampleHandler.swift
Labels: feature

#209 task #199 채팅 서버와 소켓 연결
  Projects/App/Sources/SceneDelegate.swift
  Projects/Features/LiveStreamFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/LiveStreamFeature/Interface/LiveStreamViewControllerFactory.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFractoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamViewControllerFactory.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Modules/ChatSoketModule/Sources/Message/ChatMessage.swift
  Projects/Modules/ChatSoketModule/Sources/Message/MessageType.swift
  Projects/Modules/ChatSoketModule/Sources/WebSocket.swift
Labels: feature

#213 task #212 닉네임 유효성 검사 및 저장
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignUpViewModel.swift
Labels: feature, chore

#222 task #216 유저등록 화면 애니메이션 구성
  Package.resolved
  Package.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Projects/Features/AuthFeature/Project.swift
  Projects/Features/AuthFeature/Sources/SignUpGradientView.swift
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignUpViewModel.swift
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/confetti.json
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/shook.json
Labels: design

#224 epic 유저 등록 구현
  Package.resolved
  Package.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/Dependency+SPM.swift
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Features/AuthFeature/Demo/Resources/LaunchScreen.storyboard
  Projects/Features/AuthFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/AuthFeature/Interface/Interface.swift
  Projects/Features/AuthFeature/Project.swift
  Projects/Features/AuthFeature/Sources/SignUpGradientView.swift
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignUpViewModel.swift
  Projects/Features/AuthFeature/Tests/AuthFeatureTest.swift
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/appIcon_small.imageset/Contents.json
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/appIcon_small.imageset/appIcon_small@2x.png
  Projects/UserInterfaces/DesignSystem/Resources/Image.xcassets/appIcon_small.imageset/appIcon_small@3x.png
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/confetti.json
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/shook.json
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: feature

#231 task #230 비디오 스트리밍 관련 Entity, DTO 구현
  Projects/Domains/LiveStationDomain/Interface/Entity/VideoEntity.swift
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Interface/UseCase/FetchVideoListUsecase.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/VideoListResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
  Projects/Domains/LiveStationDomain/Sources/UseCase/FetchVideoListUsecaseImpl.swift
Labels: chore

#233 task #230 레포지토리와 usecase 구현
  Projects/App/Sources/SceneDelegate.swift
  Projects/Features/LiveStreamFeature/Interface/LiveStreamViewControllerFactory.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFractoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamViewControllerFactory.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
Labels: feature

#217 task #214 채팅 System 알림 UI 구현
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/SystemAlarmCell.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: feature, chore

#234 task #230 Connect usecase to LiveStream view
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/ShookPlayerView.swift
Labels: feature

#229 task #226 방송 도메인 생성
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/Domains/BroadcastDomain/Interface/Interface.swift
  Projects/Domains/BroadcastDomain/Project.swift
  Projects/Domains/BroadcastDomain/Sources/Sources.swift
  Projects/Domains/BroadcastDomain/Testing/Testing.swift
  Projects/Domains/BroadcastDomain/Tests/BroadcastDomainTest.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/MainFeature/Project.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: chore

#235 task #215 `최근 채팅으로 이동` 버튼 구현
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
Labels: feature

#237 story 채팅 디테일 수정
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/SystemAlarmCell.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: feature

#232 task #225 런치스크린, 온보딩, 메인 뷰 연결
  Projects/App/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Projects/App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/SplashGradientView.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/App/Sources/Splash/SplashViewModel.swift
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignUpViewModel.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
Labels: feature, chore

#238 epic 채팅 구현
  Projects/App/Sources/SceneDelegate.swift
  Projects/Features/LiveStreamFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Models/ChatInfo.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/SystemAlarmCell.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFactoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFractoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Modules/ChatSoketModule/Sources/Message/ChatMessage.swift
  Projects/Modules/ChatSoketModule/Sources/Message/MessageType.swift
  Projects/Modules/ChatSoketModule/Sources/WebSocket.swift
Labels: feature

#245 task #227 방송 도메인 구현
  Projects/Domains/BroadcastDomain/Interface/Entity/BroadcastEntity.swift
  Projects/Domains/BroadcastDomain/Interface/Interface.swift
  Projects/Domains/BroadcastDomain/Interface/Repository/BroadcastRepository.swift
  Projects/Domains/BroadcastDomain/Interface/Usecase/DeleteBroadcastUsecase.swift
  Projects/Domains/BroadcastDomain/Interface/Usecase/FetchAllBroadcastUsecase.swift
  Projects/Domains/BroadcastDomain/Interface/Usecase/MakeBroadcastUsecase.swift
  Projects/Domains/BroadcastDomain/Sources/DTO/BroadcastDTO.swift
  Projects/Domains/BroadcastDomain/Sources/Endpoint/BroadcastEndpoint.swift
  Projects/Domains/BroadcastDomain/Sources/Repository/BroadcastRepositoryImpl.swift
  Projects/Domains/BroadcastDomain/Sources/Sources.swift
  Projects/Domains/BroadcastDomain/Sources/Usecase/DeleteBroadcastUsecaseImpl.swift
  Projects/Domains/BroadcastDomain/Sources/Usecase/FetchAllBroadcastUsecaseImpl.swift
  Projects/Domains/BroadcastDomain/Sources/Usecase/MakeBroadcastUsecaseImpl.swift
Labels: feature

#250 task #247 닉네임 적용
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: feature, chore

#246 task #241 `방송시작` 버튼 클릭 시 방송 채널 및 채팅방 생성
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/Domains/LiveStationDomain/Interface/Entity/ChannelInfoEntity.swift
  Projects/Domains/LiveStationDomain/Interface/Repository/LiveStationRepository.swift
  Projects/Domains/LiveStationDomain/Interface/UseCase/CreateChannelUsecase.swift
  Projects/Domains/LiveStationDomain/Interface/UseCase/FetchChannelInfoUsecase.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelInfoResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Endpoint/LiveStationEndpoint.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
  Projects/Domains/LiveStationDomain/Sources/UseCase/CreateChannelUsecaseImpl.swift
  Projects/Domains/LiveStationDomain/Sources/UseCase/FetchChannelInfoUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Demo/Sources/MockCreateChannelUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/MockFetchChannelInfoUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/MockMakeChatRoomUseCaseImpl.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
Labels: feature

#251 hotfix output을 함수 스코프 안으로 옮겨 self를 제거햇씁니다.
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
Labels: bug

#256 task #255 채널삭제 usecase 구현
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/Domains/LiveStationDomain/Interface/UseCase/DeleteChannelUsecase.swift
  Projects/Domains/LiveStationDomain/Sources/UseCase/DeleteChannelUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Demo/Sources/MockDeleteChannelUsecaseImpl.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
Labels: chore

#259 task #258 chatting domain 삭제
  Plugin/DependencyPlugin/ProjectDescriptionHelpers/ModulePaths.swift
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/Domains/ChattingDomain/Project.swift
  Projects/Features/LiveStreamFeature/Project.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFactoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewModels/LiveStreamViewModel.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Demo/Sources/MockMakeChatRoomUseCaseImpl.swift
  Projects/Features/MainFeature/Project.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Tuist/ProjectDescriptionHelpers/Extensions/Target+Extension.swift
Labels: chore

#261 task hotfix decoding error 해결
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelListResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/DTO/Response/ChannelResponseDTO.swift
  Projects/Domains/LiveStationDomain/Sources/Repository/LiveStationRepositoryImpl.swift
Labels: fix

#262 task 브로드캐스트 도메인 적용
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/Domains/BroadcastDomain/Interface/Entity/BroadcastInfoEntity.swift
  Projects/Domains/BroadcastDomain/Interface/Repository/BroadcastRepository.swift
  Projects/Domains/BroadcastDomain/Interface/Usecase/FetchAllBroadcastUsecase.swift
  Projects/Domains/BroadcastDomain/Sources/DTO/BaseDTO.swift
  Projects/Domains/BroadcastDomain/Sources/Repository/BroadcastRepositoryImpl.swift
  Projects/Domains/BroadcastDomain/Sources/Usecase/FetchAllBroadcastUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Demo/Sources/MockDeleteBroadcastUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/MockFetchAllBroadcastUsecaseImpl.swift
  Projects/Features/MainFeature/Demo/Sources/MockMakeBroadcastUsecaseImpl.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/SmallBroadcastCollectionViewCell.swift
  Projects/Modules/ChatSoketModule/Sources/Message/MessageType.swift
Labels: feature

#265 task #264 다크모드만 지원되도록 설정
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatEmptyView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatInputField.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/SystemAlarmCell.swift
  Projects/Features/LiveStreamFeature/Sources/Player/Views/ShookPlayerView.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamingViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/BroadcastThumbnailView.swift
  Projects/Features/MainFeature/Sources/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/SettingTableViewCell.swift
  Projects/Features/MainFeature/Sources/SettingUIViewController.swift
  Projects/Modules/ChatSoketModule/Sources/SoketTestViewController.swift
  Projects/Modules/EasyLayoutModule/Demo/Sources/ViewController.swift
  Tuist/ProjectDescriptionHelpers/Extensions/InfoPlist+Extension.swift
Labels: chore

#267 task #253 뷰 로딩, 디테일 수정
  Projects/Features/AuthFeature/Project.swift
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChatEmptyView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingCell.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/ChattingListView.swift
  Projects/Features/LiveStreamFeature/Sources/Chating/Views/SystemAlarmCell.swift
  Projects/Features/MainFeature/Sources/BroadcastCollectionLoadView.swift
  Projects/Features/MainFeature/Sources/Utilities/CollectionViewCellTransitioning.swift
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/ViewControllers/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/ViewModels/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionLoadView.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionViewCell/EmptyBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionViewCell/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionViewCell/SmallBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastThumbnailView.swift
  Projects/Features/MainFeature/Sources/Views/PaddingLabel.swift
  Projects/Features/MainFeature/Sources/Views/SettingTableViewCell.swift
  Projects/Modules/ThirdPartyLibModule/Project.swift
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/loading.json
  Projects/UserInterfaces/DesignSystem/Sources/SHLoadingView.swift
  Projects/UserInterfaces/DesignSystem/Sources/SHRefreshControl.swift
Labels: design, chore

#268 task #266 Change Splash
  Projects/App/Sources/SceneDelegate.swift
  Projects/App/Sources/Splash/EmptyViewModel.swift
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/App/Sources/Splash/SplashViewModel.swift
  Projects/UserInterfaces/DesignSystem/Resources/Lottie/splash.json
Labels: design

#269 task hotfix 플레이어 화면표시 딜레이 개선
  Projects/Features/LiveStreamFeature/Sources/Player/Views/ShookPlayerView.swift
Labels: fix, design

#270 task hotfix 썸네일 새로고침 오류 해결
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastCollectionViewController.swift
  Projects/Features/MainFeature/Sources/ViewModels/BroadcastCollectionViewModel.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionViewCell/LargeBroadcastCollectionViewCell.swift
  Projects/Features/MainFeature/Sources/Views/BroadcastCollectionViewCell/SmallBroadcastCollectionViewCell.swift
Labels: feature, fix

#271 task 메인 뷰, 플레이어 뷰 연결
  Projects/Features/LiveStreamFeature/Interface/LiveStreamViewControllerFactory.swift
  Projects/Features/LiveStreamFeature/Sources/Factory/LiveStreamViewControllerFactoryImpl.swift
  Projects/Features/LiveStreamFeature/Sources/Player/ViewControllers/LiveStreamViewController.swift
  Projects/Features/MainFeature/Demo/Sources/MockLiveStreamViewControllerFactory.swift
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastCollectionViewController.swift
Labels: chore

#272 task network 모듈 테스트 형식을 URLSessionConfiguration을 이용하도록 합니다.
  Projects/Modules/NetworkModule/Tests/NetworkClientTest.swift
Labels: test

#275 task #273 채널 생성 및 삭제 시점 변경
  Projects/App/Sources/Splash/SplashViewController.swift
  Projects/Features/AuthFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/AuthFeature/Demo/Sources/MockCreateChannelUsecaseImpl.swift
  Projects/Features/AuthFeature/Sources/SignUpViewController.swift
  Projects/Features/AuthFeature/Sources/SignUpViewModel.swift
  Projects/Features/MainFeature/Demo/Sources/AppDelegate.swift
  Projects/Features/MainFeature/Sources/ViewControllers/BroadcastUIViewController.swift
  Projects/Features/MainFeature/Sources/ViewControllers/SettingUIViewController.swift
  Projects/Features/MainFeature/Sources/ViewModels/BroadcastCollectionViewModel.swift
Labels: chore
